#!/usr/bin/env ruby

VERSION = "0.1.0"

require_relative 'usage'

def version
    puts "blossom v#{VERSION}"
end

def run(program_file:, graph_input:, output_file:, verbose:, tracing:, trace_dir:, colour_strategy:, keep_rationals:, output_type:, validate_only:)
    p program_file
    p graph_input
    p keep_rationals
    p tracing
end

args = Options.parse

p args
puts

if args.version
    version
else
    args.delete_field("version")
    run(**args.to_h)
end

# send(BlossomUsage.action, **BlossomUsage.options) if BlossomUsage.action
